/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cleung' at '1/8/18 8:27 PM' with Gradle 2.14.1
 *
 * @author cleung, @date 1/8/18 8:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
